### ISSUE TITLE
Main Class not found

### ISSUE THREAD

**Issue by GreatGodOfFire** [mattwright324/windows-smb-cracker#2]
I have Ubuntu 16.04 and if I want to run the Jar, it doesn't work. the output is: _Error: Could not find or load main class mattw.cracker.smb.Cracker_.

**Comment by mattwright324** [comment]
The jar requires Java 8 and JavaFX, what version of Java do you have installed?

**Comment by GreatGodOfFire** [comment]
I have openjdk 1.8.0_222

**Comment by GreatGodOfFire** [comment]
Now I installed JDK 13.0.1, but now I have the error: Error: _Could not find or load main class mattw.cracker.smb.Cracker
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application_.

**Comment by GreatGodOfFire** [comment]
Now I installed JDK 1.8.0 and it works :).

**Comment by mattwright324** [comment]
OpenJDK does not include JavaFX by default like OracleJDK does. You'll have to install openjfx 8 as well.

Since you are on 16.04, I'm not certain how it will behave but you may be able to just do `sudo apt install openjfx` and be good to go. I was using 19.04 and openjfx installs version 11 which is incompatible with OpenJDK 8 and [required additional steps to get](https://askubuntu.com/a/1163546/526249).

Sounds like you just installed OracleJDK? That or openjfx would be valid solutions.

**Comment by mattwright324** [comment]
Closing since you said it works
